// Generated by CoffeeScript 2.3.1
(function() {
  var addToTR, escapeHtml, replaceTag, tagsToReplace;

  document.add = function() {
    var e;
    e = document.getElementById('iSymbol');
    return $.getJSON('https://api.iextrading.com/1.0/stock/' + e.value + '/earnings', function(data) {
      var tr;
      e.value = '';
      tr = document.createElement('tr');
      addToTR(data.symbol);
      return document.getElementById('titems').appendChild(tr);
    });
  };

  tagsToReplace = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&rt;'
  };

  replaceTag = function(tag) {
    return tagsToReplace[tag] || tag;
  };

  escapeHtml = function(s) {
    return s.replace(/[&<>]/g, replaceTag);
  };

  addToTR = function(tr, cont) {
    var td;
    td = document.createElement('td');
    td.innerHTML = escapeHtml(cont);
    return tr.appendChild(td);
  };

}).call(this);
